name: Run main.py on schedule

on:
  schedule:
    # Run the workflow every three hours
    - cron: "0 */3 * * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    env: # Define environment variables for the entire job
      PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}

    steps:
      # Step 1: Check out the code
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Match your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run the script
      - name: Run main.py
        run: python main.py
